[FIX] l10n_it_financial_statement_eu: Ordering field must be in view
Otherwise, when opening a line from the list view:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://oca-l10n-italy-16-0-pr3599-6f592ebc11da.runboat.odoo-community.org/web/assets/444-826ea0b/web.assets_common.min.js:1472:101)
    at owl.App.handleError (http://oca-l10n-italy-16-0-pr3599-6f592ebc11da.runboat.odoo-community.org/web/assets/444-826ea0b/web.assets_common.min.js:2100:29)
    at ComponentNode.initiateRender (http://oca-l10n-italy-16-0-pr3599-6f592ebc11da.runboat.odoo-community.org/web/assets/444-826ea0b/web.assets_common.min.js:1562:19)

Caused by: TypeError: Cannot read properties of undefined (reading 'type')
    at compareRecords (http://oca-l10n-italy-16-0-pr3599-6f592ebc11da.runboat.odoo-community.org/web/assets/445-43c5a33/web.assets_backend.min.js:8267:246)
    at stableCompare (http://oca-l10n-italy-16-0-pr3599-6f592ebc11da.runboat.odoo-community.org/web/assets/444-826ea0b/web.assets_common.min.js:6091:145)
    at Array.sort (<anonymous>)
    at Object.stableSort (http://oca-l10n-italy-16-0-pr3599-6f592ebc11da.runboat.odoo-community.org/web/assets/444-826ea0b/web.assets_common.min.js:6091:102)
    at Class._sortList (http://oca-l10n-italy-16-0-pr3599-6f592ebc11da.runboat.odoo-community.org/web/assets/445-43c5a33/web.assets_backend.min.js:8270:54)
    at http://oca-l10n-italy-16-0-pr3599-6f592ebc11da.runboat.odoo-community.org/web/assets/445-43c5a33/web.assets_backend.min.js:8237:113
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Class.load (http://oca-l10n-italy-16-0-pr3599-6f592ebc11da.runboat.odoo-community.org/web/assets/445-43c5a33/web.assets_backend.min.js:7927:244)
    at async Record.load (http://oca-l10n-italy-16-0-pr3599-6f592ebc11da.runboat.odoo-community.org/web/assets/445-43c5a33/web.assets_backend.min.js:2347:77)